name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-conflicts:
    name: Check for Merge Conflicts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect merge conflicts
        run: |
          if git ls-files -u | grep -q .; then
            echo "Merge conflict detected!"
            exit 1
          else
            echo "No merge conflicts."
          fi

  install-and-build:
    name: Install, Lint, Type Check, Test, Build
    runs-on: ubuntu-latest
    needs: check-conflicts

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm lint

      - name: Type Check
        run: pnpm check-types

      - name: Run Tests
        run: pnpm test

      - name: Build Project
        run: pnpm build

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-turbo-
